server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.109:3306/hmdp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  jackson:
    default-property-inclusion: always # JSON处理时忽略非空字段
  data:
    redis:
      port: 16379
      host: 192.168.1.209
  rabbitmq:
    host: 192.168.1.209
    port: 5672
    username: daming
    password: daming
    listener:
      simple:
        concurrency: 1
        prefetch: 1
        acknowledge-mode: manual
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
